categories:
- info
- howtouse
- reviewbay
- chatbot
conversation:
- - What is the use for the site ?
  - Our aim is to analyze the data and make it available for people to use.
- - Where can I do the analysis ?
  - You need to register in order to avail the complete use.
- - What are the highlights of this program ?
  - We provide an complete feedback for your data and with our dashboard you can avail the ready to go analysis.
- - What is this site used for?
  - We provide an platform to analyze the tools and make it an worthwhile experience for the user.      
